runs:
  using: "composite"
  steps:
  - name: Установка yarn
    run: |
        yarn policies set-version 1.19.1
        echo "::set-output name=cache_dir::$(yarn cache dir)"
  - name: Настройка кэширования зависимостей
    uses: actions/cache@v2
    with:
      path: ${{ steps.yarn-setup.outputs.cache_dir }}
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
        ${{ runner.os }}-yarn-
  - name: Установка зависимостей
    run: yarn --frozen-lockfile
