name: Сборка Конструктора
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: gpn-components

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_REGISTRY_TOKEN }}
        working-directory: ./gpn-components

      - run: yarn storybook:build
        working-directory: ./gpn-components

      - uses: ./actions/deploy-static-site/v1beta1
        with:
          project-id: gpn-components
          files: ./gpn-components/build/storybook
          auth: ${{ secrets.CDN_UPLOAD_SECRET }}
          token: ${{ secrets.GITHUB_TOKEN }}
